sprint-10
mahlenko/unsplash-practicum pull request #3
Opened 2023-01-12 19:20 UTC by mahlenko

2023-01-13 20:41 UTC, mmbabaev requested changes

2023-01-13 20:41 UTC, mmbabaev commented on UnsplashPracticum/Services/NetworkService.swift
> +                // todo: попробовать сделать локализацию ошибок, когда нибудь :D
Принято называть `// TODO: ххх`, тогда xcode будет подсвечивать этот комментарий

2023-01-13 20:41 UTC, mmbabaev commented on UnsplashPracticum/Services/NetworkService.swift
> +        request.httpMethod = "\(method)"
лучше сделать `enum FetchMethod: String` и использовать здесь `.rawValue`

2023-01-13 20:44 UTC, mmbabaev approved these changes

2023-01-14 11:00 UTC, mahlenko commented on UnsplashPracticum/Services/NetworkService.swift
> +        request.httpMethod = "\(method)"
Согласен, спасибо

2023-01-14 11:01 UTC, mahlenko commented on UnsplashPracticum/Scenes/Auth/Services/TokenStorage/OAuth2TokenStorageKeychain.swift
> +        get { nil }
Вроде в спринтах было сообщение о том что после будет переход на keychain, сделал пока просто заглушку. Уберу пока, спасибо

2023-01-14 11:03 UTC, mahlenko commented
Complete sprint-10

2023-01-14 11:08 UTC, merged