Sprint-11
mahlenko/unsplash-practicum pull request #4
Opened 2023-01-29 18:38 UTC by mahlenko

2023-01-30 18:30 UTC, IBDesignable requested changes

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +                self.fetchUserProfile(username: profile.username, token: token)
ты делает переход на новый вью контроллер, который заменяет rootViewController у виндоу – повезет, если запрос профиля успеет выполниться, но в общем случае гарантий нет. Поэтому лучше дождаться завершения всей работы, отключить вентилятор(UIBlockingProgressHUD) и только потом свитчевать на следующий флоу

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +                ErrorToast.show(message: error.localizedDescription)
здесь не хватает UIBlockingProgressHUD.dismiss()

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
Я не нашла где ты переводишь на главную очередь, поэтому полагаю что не переводишь :) 

обновления UI не на главном потоке может приводить к крашу. Я бы добавила здесь оборачивание всего switch в DisptachQ.Main

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
вызови явно на AuthViewController, пожалуйста, чтобы не вводить читателя в заблуждение :) а то по коду как будто дисмисится SplashViewController

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +                break
уже ж в одном месте показываешь ошибку, а здесь почему-то оставил:

ErrorToast.show(message: error.localizedDescription)

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Services/ErrorToast.swift
> +        print(message)
Принты по всему проекту лучше подчистить

2023-01-30 18:30 UTC, IBDesignable commented on UnsplashPracticum/Services/NetworkService.swift
> +                completion(.failure(NetworkError.requiredAuthorization))
надо сделать return, иначе вдруг тебе вернут какой-то объект, ты после ошибки дальше пойдешь выполняться

2023-02-02 10:36 UTC, mahlenko commented on UnsplashPracticum/Scenes/Profile/Requests/UserProfileRequest.swift
> +                        userInfo: ["userProfile": userProfileModel])
у меня внутри функции fetch - переход в главную очередь (единственное, только в случае успешного исхода, что скорее не совсем корректно), все запросы к сети идут через эту функцию. Или я не прав, и по итогу не в главной очереди будет выполняться? Кстати как можно следить за очередями, и понимать в какой очереди? 

Там уже, в методе fetch обработка повторных запросов в сеть. Это из NetworkService.swift - все мои *Request наследуются от него

2023-02-02 10:45 UTC, mahlenko commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +                UIBlockingProgressHUD.dismiss()
внутри функции fetch - переход в главную очередь) надеюсь он работает, проверить переходит от туда в гл. очередь или нет, не знаю как. Выше писал про это тоже )

2023-02-02 10:47 UTC, mahlenko commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
если правильно понял, что нужно сделать тут, то это был пример из кода предоставленный практикумом.
Я понял что, нужно вытащить getTokenAuthorize из dismiss. Если так то, последовал примеру практикума

2023-02-02 10:49 UTC, mahlenko commented on UnsplashPracticum/Services/NetworkService.swift
> +                completion(.failure(NetworkError.requiredAuthorization))
да, точно

2023-02-02 19:57 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
Предлагаю проанализировать вот эти три строчки:

```
self.dismiss(animated: true) 
dismiss(animated: true)
viewController.dismiss(animated: true)
```
и что с точки зрения ревьювера/читателя этих строк, ты ожидаешь от выполнения этих строк

2023-02-02 19:58 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
> Если так то, последовал примеру практикума

Можешь привести цитату?

2023-02-02 19:59 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
На самом деле, оба варианта будут пытаться закрыть самый верхний презентуемый контент (или себя, если это верхний) 

Что к сожалению с точки зрения читателя может вводить в заблужение.

2023-02-02 20:04 UTC, mahlenko commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
> Предлагаю проанализировать вот эти три строчки:
> 
> ```
> self.dismiss(animated: true) 
> dismiss(animated: true)
> viewController.dismiss(animated: true)
> ```
> 
> и что с точки зрения ревьювера/читателя этих строк, ты ожидаешь от выполнения этих строк

первые 2 по сути полностью идентичны, и закрою то окно, в классе которого они написаны - в данном случае) 3 закроет viewController.

> Можешь привести цитату
Сейчас найду) это где-то в прикрепленном архиве было

2023-02-02 20:10 UTC, mahlenko commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
Спринт 10 "Splash самостоятельная задача" в конце скачать авторское решение, файл SplashViewController.

```
extension SplashViewController: AuthViewControllerDelegate {
    func authViewController(_ vc: AuthViewController, didAuthenticateWithCode code: String) {
        dismiss(animated: true) { [weak self] in
            guard let self = self else { return }
            self.fetchOAuthToken(code)
        }
    }
```

2023-02-02 20:11 UTC, IBDesignable commented
@mahlenko 

Не вижу изменений по пункту:

> Устранено состояние гонки в OAuth2Service
> ❌ обработан повторный вызов fetchAuthToken() с одинаковым code
> ❌ обработан повторный вызов fetchAuthToken() с новым code

2023-02-02 20:11 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Profile/ProfileViewController.swift
> +        logoutButton.topAnchor.constraint(equalTo: avatarImageView.centerYAnchor, constant: -11).isActive = true
Попробуй следовать рекомендации учебника и эпол и использовать  NSLayoutConstraint.activate([ констрейнты ]), чтобы сделать это за один вызов. В доке обещают что это сработает эффективнее, чем поштучная активация

2023-02-02 20:11 UTC, IBDesignable commented on UnsplashPracticum/Services/NetworkService.swift
> +            DispatchQueue.main.async {
окей, нашла, засчитываю!


На вопрос о том, как определить вызывается ли с правильной очереди – достаточно просто поставить брейкпонит напротив подозреваемой строчки и посмотреть в дебаг навигаторе разбивку по тредам:
<img width="1099" alt="Снимок экрана 2023-02-02 в 22 07 42" src="https://user-images.githubusercontent.com/121577115/216438550-c44f8f2c-5d9c-420a-8ec4-1c517f7e3c77.png">

2023-02-02 20:16 UTC, IBDesignable commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
> первые 2 по сути полностью идентичны, и закрою то окно, в классе которого они написаны - в данном случае) 3 закроет viewController.

Отлично! вот и я о том же. Когда видишь dismiss на self – кажется, что он будет закрывать сплеш – что бессмысленно, потому что это корневой вью контроллер, он не может задисмиситься. 

Но на самом деле тут должно быть желание закрывть authVC – и хочется видеть именно третий вариант, чтобы однозначно понимать твои намеренья. 

Но по факту происходит не ожидаемое хитрое поведение :) и авторское решение работает идентично viewController.dismiss. 

Оставляю решение за тобой. Авторам отнесу предложение уточнить этот пункт.

2023-02-02 20:17 UTC, mahlenko commented on UnsplashPracticum/Services/NetworkService.swift
> +            DispatchQueue.main.async {
> окей, нашла, засчитываю!
> 
> На вопрос о том, как определить вызывается ли с правильной очереди – достаточно просто поставить брейкпонит напротив подозреваемой строчки и посмотреть в дебаг навигаторе разбивку по тредам: <img alt="Снимок экрана 2023-02-02 в 22 07 42" width="1099" src="https://user-images.githubusercontent.com/121577115/216438550-c44f8f2c-5d9c-420a-8ec4-1c517f7e3c77.png">

Спасибо, попробую, по экспериментирую)))

2023-02-02 20:18 UTC, IBDesignable commented on UnsplashPracticum/Services/NetworkService.swift
> +
не очевидно попрятал. принято

2023-02-02 20:21 UTC, mahlenko commented on UnsplashPracticum/Scenes/Splash/SplashViewController.swift
> +        dismiss(animated: true) {
> Но по факту происходит не ожидаемое хитрое поведение :) и авторское решение работает идентично viewController.dismiss.
> 
> Оставляю решение за тобой. Авторам отнесу предложение уточнить этот пункт.

Я обновил это место на более понятное)

```
func authViewController(_ viewController: AuthViewController, didAuthenticateWithCode code: String) {
        viewController.dismiss(animated: true) { [weak self] in
            guard let self = self else {
                return
            }
            self.getTokenAuthorize(code: code)
        }
    }
```

2023-02-02 20:26 UTC, IBDesignable commented on UnsplashPracticum/Services/NetworkService.swift
> +
да, и такие конструкции лучше через guard писать

2023-02-02 20:33 UTC, mahlenko commented on UnsplashPracticum/Services/NetworkService.swift
> +
> да, и такие конструкции лучше через guard писать

Спасибо, постараюсь учесть в 12 спринте. Он готов, только что смержить 11 с 12 надо. В первой половине дня пришлю и его на ревью

2023-02-02 20:41 UTC, merged