sprint-12
mahlenko/unsplash-practicum pull request #5
Opened 2023-02-10 11:54 UTC by mahlenko

2023-02-10 12:00 UTC, mahlenko commented
Похоже у меня добавлены только те изменения, что были сделаны после объединения с 11 спринтом. Как можно добавить все? Или получится разобраться?)

Я в файле ImageListViewController написал, но тут продублирую. По ТЗ там требуется, пока фото загружаются поставить анимацию градиента, я ее заменил на blurHash (хеш с размытым фоном, похожий на загружаемое изображение) - так как увидел, что Unsplash дает такие данные. А уже на экране профиля, оставил анимацию загрузки как по ТЗ.

2023-02-10 22:50 UTC, mmbabaev requested changes

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +            var picture = PhotoRequest.shared.photos[indexPath.row] as? PhotoViewModel
обращайте внимание на ворнинги, этот каст не нужен
<img width="722" alt="Screenshot 2023-02-11 at 00 59 17" src="https://user-images.githubusercontent.com/12600807/218207075-6a095c91-a41d-47a7-a822-a5a5de2770f1.png">

2023-02-10 22:50 UTC, mmbabaev commented on Tests/PhotoRequestTest.swift
> +        let service = PhotoRequest(urlSession: URLSession.shared)
Хорошо, что написали доп тест, но вообще хороший тест не должен зависеть от сети. URLSession.shared должна быть использована под протоколом и замокана

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Extensions/UIView.swift
> +        if let label = self as? UILabel { label.text = " " }
так не очень хорошо делать. Во-первых, у вас есть частный случай с Label и вы его обрабатываете в общем методе UIView. Во-вторых это потенциальный источник багов и непонимания что происходит. Разработчик-пользователь кода может быть удивлен, что этот метод очищает текст лейбла



Вы явно вызываете метод, можно реализовать у UILabel доп метод: 
```
shimmerAnimatePlaceholderAndRemoveText {
  shimmerAnimatePlaceholder()
  text = ""
}
```

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +        let photoCount = PhotoRequest.shared.photos.count
PhotoRequest по-факту является не реквестом (запросом), а сервисом, который хранит текущее состояние фотографий (нейминг непонятен)

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +        let photoCount = PhotoRequest.shared.photos.count
также можно не использовать синглтоны хотя бы в функциях, убрать PhotoRequest.shared в поля класса

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +            case .success: break
непонятно почему вы решили обработать success случай в Notification Center (это плохой способ), а тут сделали просто break

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/SingleImage/SingleImageViewController.swift
> +import Drops
этот импорт не нужен, вы сделали класс-обертку

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/SingleImage/SingleImageViewController.swift
> +import Drops
enum точнее

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/Profile/ProfileViewController.swift
> +        HTTPCookieStorage.shared.removeCookies(since: Date.distantPast)
можно вынести в отдельный класс эту работу

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/Profile/ProfileViewController.swift
> +        avatarImageView.shimmerAnimatePlaceholder(color: Shimmer.color)
мб имеет смысл дефектный параметр `color = Shimmer.color` поставить, раз он везде используется

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Request/PhotoRequest.swift
> +                        let photos = try JSONDecoder().decode([PhotoModel].self, from: data)
JSONDecoder можно перенести в отдельную переменную, это относительно дорогая операция

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Request/PhotoRequest.swift
> +                        let photos = try JSONDecoder().decode([PhotoModel].self, from: data)
(его создание)

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Request/PhotoRequest.swift
> +        guard let token = OAuth2TokenStorage().userToken else {
OAuth2TokenStorage() делает класс нетестируемым, по-хорошему нужно это вынести в отдельную зависимость и передавать через init

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Request/PhotoRequest.swift
> +class PhotoRequest: NetworkService {
предлагаю использовать композицию, вместо наследования. 

Используйте в своих Request (сервисах) NetworkService как отдельную переменную. Тогда ее можно будет замокать, если использовать протокол и подменять в тестах

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +                // FIXME: тут я не использовал как по ТЗ анимацию градиента, увидел что в API возращается blurHash решил попробовать использовать его. Анимацию градиента использую только в профиле. Н
хорошо, интересно

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +        cell.dateLabel.text = (picture.createdAt != nil) ? dateFormatter.string(from: picture.createdAt!) : ""
` = picture.createdAt.map { dateFormatter.string(from: $0) } ?? ""
`

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +            cell.likeButton.imageView?.image = UIImage(named: "heart-active")
так выставлять картинку у кнопки нельзя, это приводит к такому багу. 

https://user-images.githubusercontent.com/12600807/218214127-be4087a5-8f64-4e64-b314-869ce35c676d.mp4


Нужно использовать `setImage`
https://developer.apple.com/documentation/uikit/uibutton/1623997-setimage

Насколько я понимаю, на `viewDidAppear` `UIButton` расставляет, картинку, основываясь на своем состоянии `normal`, поэтому выставляется nil, если оно не проставлено

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Model/PhotoModel.swift
> +    private enum CodingKeys: String, CodingKey {
Для информации: вместо переопределения `CodingKeys` можно использовать`keyDecodingStrategy/keyEncodingStrategy` https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/Model/PhotoViewModel.swift
> +            createdAt: DateFormatter().date(from: model.createdAt),
здесь всегда nil, в дефектном форматтере не тот формат

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/ImageList/ImagesListViewController.swift
> +            case .success: break
Понял, что требования учебника учитывали.

2023-02-10 22:50 UTC, mmbabaev commented on UnsplashPracticum/Scenes/SingleImage/SingleImageViewController.swift
>          let imageToShared = [image as UIImage] as [Any]
это не нужно, ниже можно просто 
`activityItems: [image],`

2023-02-11 11:51 UTC, mahlenko commented on Tests/PhotoRequestTest.swift
> +        let service = PhotoRequest(urlSession: URLSession.shared)
Его не нужно было в гит выгружать, забыл его убрать из репозитория. Спасибо.

2023-02-11 12:37 UTC, mahlenko commented on UnsplashPracticum/Scenes/ImageList/Request/PhotoRequest.swift
> +class PhotoRequest: NetworkService {
Правильно понимаю, типа синглтона - *.shared?

2023-02-19 20:51 UTC, merged